### PR TITLE
Target more recent .NET Standard platforms

### PR DESCRIPTION
**Pull request by mfeingol**
This package should provide at least a 2.0 target. I added the usual list.

cf https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/cross-platform-targeting

### CODE REVIEW

**Comment by mfeingol** [comment]
NB: I wanted to add .NET Standard 2.1 as well, but the AppVeyor setup appears to be for VS2017, which doesn't support .NET Core 3.0.

**Comment by vivet** [comment]
It shouldn't be necessary to target all the net standard versions

**Comment by mfeingol** [comment]
That's probably true. But it's good practice to target 2.0 if you're also targeting 1.x.

```
✔️ DO include a netstandard2.0 target if you require a netstandard1.x target.

All platforms supporting .NET Standard 2.0 will use the netstandard2.0 target and benefit from having a smaller package graph while older platforms will still work and fall back to using the netstandard1.x target.
```

**Comment by mfeingol** [comment]
(As an aside, I did notice my 2.0-based app packages (for UWP and Xamarin Forms / Android) got several MB larger after referencing GoogleApi, which is more than you'd think based on assembly size alone.)

**Comment by vivet** [comment]
Just read the link, and it seems it's a good idea, for smaller package sizes when on 2.0. I will merge tomorrow

**Comment by vivet** [comment]
The updated package is available. It supports 1.1, 1.4, 2.0 and 2.1
Let me know if you have any issues.

**Pull request merged**
